from __future__ import annotations

import ast
import json
import sys
import types
import re
from collections import OrderedDict
from datetime import date, datetime
from enum import StrEnum
from pathlib import Path
from typing import Any, get_args, get_origin

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from packages.contracts.ois_contracts.contracts import (  # noqa: E402
    CONTRACT_GLOSSARY,
    CONTRACT_MODELS,
    AIContextSource,
    AIFunction,
    AssessmentKind,
    CommentVisibility,
    ConfidenceBand,
    DependencyKind,
    EscalationSeverity,
    EscalationStatus,
    FollowUpStatus,
    HelpRequestStatus,
    KnowledgeEntityKind,
    MessageAuthorRole,
    NotificationChannel,
    NotificationLevel,
    ObservationType,
    PlanStatus,
    ProgressEntryType,
    ReportKind,
    TaskEventType,
    TaskStatus,
    ThreadScope,
    VenueStatus,
    Vertical,
)

ENUM_TYPES = [
    Vertical,
    VenueStatus,
    AssessmentKind,
    ConfidenceBand,
    PlanStatus,
    TaskStatus,
    DependencyKind,
    TaskEventType,
    CommentVisibility,
    ProgressEntryType,
    ObservationType,
    HelpRequestStatus,
    FollowUpStatus,
    EscalationSeverity,
    EscalationStatus,
    NotificationChannel,
    NotificationLevel,
    ThreadScope,
    MessageAuthorRole,
    KnowledgeEntityKind,
    ReportKind,
    AIFunction,
    AIContextSource,
]

PHASE2_DIR = ROOT / "docs" / "migration" / "phase2"
FRONTEND_TS_PATH = ROOT / "packages" / "contracts" / "ois_contracts" / "frontend.ts"
CURRENT_PLATFORM_ROOT = ROOT.parent / "CODEX-VOIS-claude-debug-api-500-error-HACD2"

SCHEMA_FILES = [
    CURRENT_PLATFORM_ROOT / "apps" / "api" / "app" / "schemas" / "domain.py",
    CURRENT_PLATFORM_ROOT / "apps" / "api" / "app" / "schemas" / "copilot.py",
    CURRENT_PLATFORM_ROOT / "apps" / "api" / "app" / "schemas" / "intake.py",
    CURRENT_PLATFORM_ROOT / "apps" / "api" / "app" / "schemas" / "ai.py",
    CURRENT_PLATFORM_ROOT / "apps" / "api" / "app" / "schemas" / "files.py",
    CURRENT_PLATFORM_ROOT / "apps" / "api" / "app" / "schemas" / "ontology.py",
    CURRENT_PLATFORM_ROOT / "apps" / "api" / "app" / "api" / "routers" / "notifications.py",
]
CURRENT_FRONTEND_API = CURRENT_PLATFORM_ROOT / "apps" / "web" / "src" / "lib" / "api.ts"


def json_dump(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


def is_union(annotation: Any) -> bool:
    origin = get_origin(annotation)
    return origin in (types.UnionType, getattr(__import__("typing"), "Union", object))


def unwrap_optional(annotation: Any) -> tuple[Any, bool]:
    if not is_union(annotation):
        return annotation, False
    args = [arg for arg in get_args(annotation) if arg is not type(None)]
    if len(args) == 1 and len(args) != len(get_args(annotation)):
        return args[0], True
    return annotation, False


def render_ts_type(annotation: Any) -> str:
    annotation, optional = unwrap_optional(annotation)
    origin = get_origin(annotation)

    if annotation is Any:
        ts_type = "unknown"
    elif annotation in (str, date, datetime):
        ts_type = "string"
    elif annotation in (int, float):
        ts_type = "number"
    elif annotation is bool:
        ts_type = "boolean"
    elif origin in (list, list[str].__origin__):  # type: ignore[attr-defined]
        item_type = render_ts_type(get_args(annotation)[0])
        ts_type = f"{item_type}[]"
    elif origin in (dict, dict[str, str].__origin__):  # type: ignore[attr-defined]
        args = get_args(annotation)
        value_type = render_ts_type(args[1]) if len(args) == 2 else "unknown"
        ts_type = f"Record<string, {value_type}>"
    elif is_union(annotation):
        ts_type = " | ".join(sorted({render_ts_type(arg) for arg in get_args(annotation) if arg is not type(None)}))
    elif isinstance(annotation, type) and issubclass(annotation, StrEnum):
        ts_type = annotation.__name__
    elif isinstance(annotation, type) and any(annotation is model for model in CONTRACT_MODELS):
        ts_type = annotation.__name__
    else:
        ts_type = "unknown"

    if optional and "null" not in ts_type.split(" | "):
        ts_type = f"{ts_type} | null"
    return ts_type


def generate_typescript() -> str:
    lines: list[str] = [
        "// Generated by scripts/phase2_contract_freeze.py",
        "",
    ]

    for enum_type in ENUM_TYPES:
        members = " | ".join(f'"{member.value}"' for member in enum_type)
        lines.append(f"export type {enum_type.__name__} = {members};")
        lines.append("")

    for model in CONTRACT_MODELS:
        lines.append(f"export type {model.__name__} = {{")
        for field_name, field_info in model.model_fields.items():
            property_suffix = "?" if not field_info.is_required() else ""
            lines.append(f"  {field_name}{property_suffix}: {render_ts_type(field_info.annotation)};")
        lines.append("};")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def parse_python_schema_fields(path: Path) -> dict[str, dict[str, Any]]:
    module = ast.parse(path.read_text(encoding="utf-8"))
    classes: dict[str, dict[str, Any]] = {}
    for node in module.body:
        if not isinstance(node, ast.ClassDef):
            continue
        own_fields: list[str] = []
        for item in node.body:
            if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                own_fields.append(item.target.id)
        bases = [base.id for base in node.bases if isinstance(base, ast.Name)]
        classes[node.name] = {"own_fields": own_fields, "bases": bases, "path": str(path)}

    def resolve(name: str, seen: set[str] | None = None) -> list[str]:
        seen = seen or set()
        if name in seen or name not in classes:
            return []
        seen.add(name)
        fields: list[str] = []
        for base in classes[name]["bases"]:
            fields.extend(resolve(base, seen))
        fields.extend(classes[name]["own_fields"])
        return list(dict.fromkeys(fields))

    resolved: dict[str, dict[str, Any]] = {}
    for name, info in classes.items():
        resolved[name] = {
            "fields": resolve(name),
            "path": info["path"],
        }
    return resolved


def parse_ts_types(path: Path) -> dict[str, dict[str, Any]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    types_found: dict[str, dict[str, Any]] = {}
    i = 0
    start_re = re.compile(r"^export type (\w+) = (?:(\w+) & )?\{$")

    while i < len(lines):
        match = start_re.match(lines[i].strip())
        if not match:
            i += 1
            continue

        name, base = match.groups()
        depth = lines[i].count("{") - lines[i].count("}")
        i += 1
        own_fields: list[str] = []
        while i < len(lines) and depth > 0:
            line = lines[i]
            if depth == 1:
                field_match = re.match(r"\s*([A-Za-z_][A-Za-z0-9_]*)\??:", line)
                if field_match:
                    own_fields.append(field_match.group(1))
            depth += line.count("{") - line.count("}")
            i += 1
        types_found[name] = {"own_fields": own_fields, "base": base}

    def resolve(name: str, seen: set[str] | None = None) -> list[str]:
        seen = seen or set()
        if name in seen or name not in types_found:
            return []
        seen.add(name)
        fields: list[str] = []
        base = types_found[name]["base"]
        if base:
            fields.extend(resolve(base, seen))
        fields.extend(types_found[name]["own_fields"])
        return list(dict.fromkeys(fields))

    resolved: dict[str, dict[str, Any]] = {}
    for name, info in types_found.items():
        resolved[name] = {"fields": resolve(name), "base": info["base"]}
    return resolved


def build_contract_inventory() -> list[dict[str, Any]]:
    inventory: list[dict[str, Any]] = []
    for model in CONTRACT_MODELS:
        inventory.append(
            {
                "name": model.__name__,
                "field_count": len(model.model_fields),
                "fields": list(model.model_fields.keys()),
                "glossary": CONTRACT_GLOSSARY[model.__name__],
            }
        )
    return inventory


def build_shared_schema_bundle() -> dict[str, Any]:
    bundle = OrderedDict()
    for model in CONTRACT_MODELS:
        bundle[model.__name__] = {
            "fields": list(model.model_fields.keys()),
            "json_schema": model.model_json_schema(),
        }
    return bundle


def compare_field_sets(shared_fields: list[str], current_fields: list[str]) -> dict[str, list[str]]:
    shared_set = set(shared_fields)
    current_set = set(current_fields)
    return {
        "missing_from_current": sorted(shared_set - current_set),
        "extra_in_current": sorted(current_set - shared_set),
    }


def current_platform_mappings() -> list[dict[str, Any]]:
    return [
        {"contract": "VenueProjectContract", "backend": "VenueRead", "frontend": "Venue"},
        {"contract": "AssessmentDraftContract", "backend": "AssessmentRead", "frontend": "AssessmentRecord"},
        {"contract": "AssessmentRunRequestContract", "backend": "AssessmentRunRequest", "frontend": None},
        {"contract": "SignalContract", "backend": "IntakeSignalMatch", "frontend": None},
        {"contract": "FailureModeContract", "backend": "DiagnosticFinding", "frontend": None},
        {"contract": "ResponsePatternContract", "backend": "DiagnosticFinding", "frontend": None},
        {"contract": "BlockActivationContract", "backend": None, "frontend": None},
        {"contract": "GeneratedPlanContract", "backend": None, "frontend": None},
        {"contract": "PlanContract", "backend": "PlanRead", "frontend": "PlanRecord"},
        {"contract": "TaskContract", "backend": "PlanTaskRead", "frontend": "PlanTaskRecord"},
        {"contract": "TaskDependencyContract", "backend": None, "frontend": None},
        {"contract": "TaskEventContract", "backend": None, "frontend": None},
        {"contract": "TaskCommentContract", "backend": None, "frontend": None},
        {"contract": "ProgressEntryContract", "backend": "ProgressEntryRead", "frontend": "ProgressEntryRecord"},
        {"contract": "ObservationContract", "backend": "EvidenceRead", "frontend": "EvidenceRecord"},
        {"contract": "HelpRequestContract", "backend": None, "frontend": None},
        {"contract": "FollowUpContract", "backend": "FollowUpRead", "frontend": "FollowUpRecord"},
        {"contract": "EscalationContract", "backend": "EscalationRead", "frontend": "EscalationRecord"},
        {"contract": "ReportContract", "backend": "EngineReportOutput", "frontend": None},
        {"contract": "DiagnosticResultContract", "backend": "EngineRunOutput", "frontend": "EngineRunResponse"},
        {"contract": "NotificationSubscriptionContract", "backend": "PushSubscriptionRequest", "frontend": None},
        {"contract": "NotificationEventContract", "backend": None, "frontend": None},
        {"contract": "ChatMessageContract", "backend": "CopilotMessageRead", "frontend": "CopilotMessageRecord"},
        {"contract": "ChatThreadContract", "backend": "CopilotThreadDetail", "frontend": "CopilotThreadDetail"},
        {"contract": "KnowledgeReferenceContract", "backend": "OntologyEntityBase", "frontend": "OntologyEntityRecord"},
        {"contract": "AITraceContract", "backend": "AIInvocationAudit", "frontend": None},
        {"contract": "AIIntakeSnapshotContract", "backend": "IntakePreviewResponse", "frontend": "IntakePreviewResponse"},
    ]


def build_platform_consistency_audit() -> dict[str, Any]:
    current_backend: dict[str, dict[str, Any]] = {}
    for schema_file in SCHEMA_FILES:
        current_backend.update(parse_python_schema_fields(schema_file))

    current_frontend = parse_ts_types(CURRENT_FRONTEND_API)
    shared_frontend = parse_ts_types(FRONTEND_TS_PATH)

    shared_python_index = {model.__name__: list(model.model_fields.keys()) for model in CONTRACT_MODELS}
    shared_py_vs_ts: list[dict[str, Any]] = []
    for contract_name, fields in shared_python_index.items():
        ts_fields = shared_frontend.get(contract_name, {}).get("fields", [])
        shared_py_vs_ts.append(
            {
                "contract": contract_name,
                "status": "match" if fields == ts_fields else "mismatch",
                "python_only": sorted(set(fields) - set(ts_fields)),
                "typescript_only": sorted(set(ts_fields) - set(fields)),
            }
        )

    platform_results: list[dict[str, Any]] = []
    for mapping in current_platform_mappings():
        contract_name = mapping["contract"]
        shared_fields = shared_python_index[contract_name]
        backend_name = mapping["backend"]
        frontend_name = mapping["frontend"]

        backend_fields = current_backend.get(backend_name, {}).get("fields", []) if backend_name else []
        frontend_fields = current_frontend.get(frontend_name, {}).get("fields", []) if frontend_name else []

        backend_status = "missing" if backend_name and backend_name not in current_backend else ("not_mapped" if not backend_name else "present")
        frontend_status = "missing" if frontend_name and frontend_name not in current_frontend else ("not_mapped" if not frontend_name else "present")

        comparisons = {
            "backend": compare_field_sets(shared_fields, backend_fields) if backend_status == "present" else None,
            "frontend": compare_field_sets(shared_fields, frontend_fields) if frontend_status == "present" else None,
        }

        if backend_status == "present" and frontend_status == "present":
            aligned = not comparisons["backend"]["missing_from_current"] and not comparisons["frontend"]["missing_from_current"]
            overall_status = "aligned" if aligned else "mismatch"
        else:
            overall_status = "missing_or_partial"

        platform_results.append(
            {
                "contract": contract_name,
                "overall_status": overall_status,
                "backend": {
                    "mapped_to": backend_name,
                    "status": backend_status,
                    "field_comparison": comparisons["backend"],
                },
                "frontend": {
                    "mapped_to": frontend_name,
                    "status": frontend_status,
                    "field_comparison": comparisons["frontend"],
                },
            }
        )

    return {
        "shared_python_vs_typescript": shared_py_vs_ts,
        "current_platform_alignment": platform_results,
    }


def build_legacy_mapping_summary() -> list[dict[str, Any]]:
    return [
        {
            "legacy_payload": "project.json",
            "sample_path": str(ROOT / "docs" / "migration" / "phase0" / "fixtures" / "F004_existing_active_plan_kaunas" / "source_snapshots" / "project.json"),
            "target_contract": "VenueProjectContract",
            "fit": "partial_fit_with_acceptable_adaptation",
            "notes": "Legacy venue/project shape carries rich venue lifecycle context but omits organization/workspace ids in fixture snapshots.",
        },
        {
            "legacy_payload": "assessment.json",
            "sample_path": str(ROOT / "docs" / "migration" / "phase0" / "fixtures" / "F004_existing_active_plan_kaunas" / "source_snapshots" / "assessment.json"),
            "target_contract": "AssessmentDraftContract",
            "fit": "partial_fit_with_acceptable_adaptation",
            "notes": "Legacy assessment uses timestamp and signals keys rather than created_at and signal_states.",
        },
        {
            "legacy_payload": "fixture_input.json",
            "sample_path": str(ROOT / "docs" / "migration" / "phase0" / "fixtures" / "F006_complex_klaipeda_multi_surface" / "fixture_input.json"),
            "target_contract": "AssessmentRunRequestContract",
            "fit": "partial_fit_with_acceptable_adaptation",
            "notes": "Legacy engine input fits the request seam after renaming signals to signal_states and preserving venue context and triage fields.",
        },
        {
            "legacy_payload": "golden_normalized_signals.json",
            "sample_path": str(ROOT / "docs" / "migration" / "phase0" / "fixtures" / "F002_degraded_pegasas" / "golden_normalized_signals.json"),
            "target_contract": "SignalContract",
            "fit": "full_fit",
            "notes": "Normalized signal payload is directly represented in the frozen contract.",
        },
        {
            "legacy_payload": "golden_failure_modes.json",
            "sample_path": str(ROOT / "docs" / "migration" / "phase0" / "fixtures" / "F002_degraded_pegasas" / "golden_failure_modes.json"),
            "target_contract": "FailureModeContract",
            "fit": "full_fit",
            "notes": "Legacy failure-mode payload maps directly including score and contributing signal ids.",
        },
        {
            "legacy_payload": "golden_response_patterns.json",
            "sample_path": str(ROOT / "docs" / "migration" / "phase0" / "fixtures" / "F002_degraded_pegasas" / "golden_response_patterns.json"),
            "target_contract": "ResponsePatternContract",
            "fit": "full_fit",
            "notes": "Legacy response-pattern payload maps directly including trigger links and focus text.",
        },
        {
            "legacy_payload": "golden_activation_context.json",
            "sample_path": str(ROOT / "docs" / "migration" / "phase0" / "fixtures" / "F002_degraded_pegasas" / "golden_activation_context.json"),
            "target_contract": "BlockActivationContract",
            "fit": "full_fit",
            "notes": "Legacy activation context already carries response-pattern ids, priority, and block activations by layer.",
        },
        {
            "legacy_payload": "golden_action_plan.json",
            "sample_path": str(ROOT / "docs" / "migration" / "phase0" / "fixtures" / "F002_degraded_pegasas" / "golden_action_plan.json"),
            "target_contract": "GeneratedPlanContract",
            "fit": "full_fit",
            "notes": "Legacy generated plan is frozen as a layered engine output rather than flattened into persisted tasks.",
        },
        {
            "legacy_payload": "operational_plan.json",
            "sample_path": str(ROOT / "docs" / "migration" / "phase0" / "fixtures" / "F004_existing_active_plan_kaunas" / "source_snapshots" / "operational_plan.json"),
            "target_contract": "PlanContract",
            "fit": "partial_fit_with_acceptable_adaptation",
            "notes": "Persisted plan shape fits after flattening legacy status history into task events and retaining summary/confidence metadata in summary_snapshot.",
        },
        {
            "legacy_payload": "progress/entries.json",
            "sample_path": str(ROOT / "docs" / "migration" / "phase0" / "fixtures" / "F004_existing_active_plan_kaunas" / "source_snapshots" / "progress" / "entries.json"),
            "target_contract": "ProgressEntryContract",
            "fit": "partial_fit_with_acceptable_adaptation",
            "notes": "Legacy progress feed maps only if entry_type is preserved; current platform drops that distinction.",
        },
        {
            "legacy_payload": "chat_history/t_*.json",
            "sample_path": str(ROOT / "docs" / "migration" / "phase0" / "fixtures" / "F004_existing_active_plan_kaunas" / "source_snapshots" / "chat_history" / "t_48f81c67cfc2.json"),
            "target_contract": "ChatThreadContract",
            "fit": "partial_fit_with_acceptable_adaptation",
            "notes": "Legacy thread files fit after carrying thread scope/type into the frozen chat contract and keeping attachments/references explicit.",
        },
        {
            "legacy_payload": "ai_extraction_snapshot.json",
            "sample_path": str(ROOT / "docs" / "migration" / "phase0" / "fixtures" / "F005_ambiguous_ai_preopening_muzos2" / "ai_extraction_snapshot.json"),
            "target_contract": "AIIntakeSnapshotContract",
            "fit": "full_fit",
            "notes": "Legacy AI extraction snapshot is preserved explicitly rather than collapsed into a thin signal list.",
        },
        {
            "legacy_payload": "golden_report.md",
            "sample_path": str(ROOT / "docs" / "migration" / "phase0" / "fixtures" / "F002_degraded_pegasas" / "golden_report.md"),
            "target_contract": "ReportContract",
            "fit": "partial_fit_with_acceptable_adaptation",
            "notes": "Markdown report fits the report seam, but current platform splits markdown from structured summary/report data.",
        },
    ]


def main() -> None:
    PHASE2_DIR.mkdir(parents=True, exist_ok=True)

    FRONTEND_TS_PATH.write_text(generate_typescript(), encoding="utf-8")

    inventory = build_contract_inventory()
    glossary = CONTRACT_GLOSSARY
    schema_bundle = build_shared_schema_bundle()
    consistency_audit = build_platform_consistency_audit()
    legacy_mapping = build_legacy_mapping_summary()

    json_dump(PHASE2_DIR / "contract_inventory.json", inventory)
    json_dump(PHASE2_DIR / "contract_glossary.json", glossary)
    json_dump(PHASE2_DIR / "shared_contract_schemas.json", schema_bundle)
    json_dump(PHASE2_DIR / "consistency_audit.json", consistency_audit)
    json_dump(PHASE2_DIR / "legacy_mapping_summary.json", legacy_mapping)

    aligned = [
        item["contract"]
        for item in consistency_audit["current_platform_alignment"]
        if item["overall_status"] == "aligned"
    ]
    mismatched = [
        item["contract"]
        for item in consistency_audit["current_platform_alignment"]
        if item["overall_status"] != "aligned"
    ]
    summary = {
        "contract_count": len(CONTRACT_MODELS),
        "shared_python_vs_typescript_clean": all(
            item["status"] == "match" for item in consistency_audit["shared_python_vs_typescript"]
        ),
        "current_platform_aligned_contracts": aligned,
        "current_platform_mismatched_or_missing_contracts": mismatched,
        "legacy_full_fit_contracts": [item["target_contract"] for item in legacy_mapping if item["fit"] == "full_fit"],
        "legacy_partial_fit_contracts": [
            item["target_contract"] for item in legacy_mapping if item["fit"] != "full_fit"
        ],
    }
    json_dump(PHASE2_DIR / "summary.json", summary)

    print("Phase 2 contract freeze artifacts written.")
    print(f"Contracts frozen: {len(CONTRACT_MODELS)}")
    print(f"Shared Python/TypeScript parity clean: {summary['shared_python_vs_typescript_clean']}")
    print(f"Current platform aligned contracts: {len(aligned)}")
    print(f"Current platform mismatched or missing contracts: {len(mismatched)}")


if __name__ == "__main__":
    main()
