from functools import lru_cache

from app.schemas.ai import AIFunction, AIFunctionContract, AIContextSource, AIOutputMode, AIRiskLevel


@lru_cache
def get_ai_contract_registry() -> dict[AIFunction, AIFunctionContract]:
    return {
        AIFunction.SIGNAL_INTAKE: AIFunctionContract(
            function=AIFunction.SIGNAL_INTAKE,
            purpose="Convert messy operational evidence into structured signal suggestions with confidence and evidence refs.",
            risk_level=AIRiskLevel.MEDIUM,
            output_mode=AIOutputMode.STRUCTURED_JSON,
            context_sources=[AIContextSource.RAW_TEXT_INPUT, AIContextSource.SIGNAL_LIBRARY, AIContextSource.ONTOLOGY],
            requires_user_confirmation=True,
            requires_structured_output=True,
            system_prompt_version="v1",
            allowed_actions=["extract_signals", "extract_quantitative_evidence", "flag_unmapped_observations"],
            prohibited_actions=["invent_signal_ids", "mutate_signal_state_without_review"],
        ),
        AIFunction.VENUE_COPILOT: AIFunctionContract(
            function=AIFunction.VENUE_COPILOT,
            purpose="Act as the venue-level operational copilot grounded in venue state, plans, tools, and evidence.",
            risk_level=AIRiskLevel.HIGH,
            output_mode=AIOutputMode.CONVERSATIONAL,
            context_sources=[
                AIContextSource.VENUE_STATE,
                AIContextSource.SIGNAL_STATE,
                AIContextSource.PLAN_STATE,
                AIContextSource.BLOCK_LIBRARY,
                AIContextSource.TOOL_LIBRARY,
                AIContextSource.KNOWLEDGE_BASE,
                AIContextSource.THREAD_HISTORY,
                AIContextSource.FILE_UPLOADS,
            ],
            requires_user_confirmation=True,
            system_prompt_version="v1",
            allowed_actions=["explain_reasoning", "coach_execution", "propose_signal_updates"],
            prohibited_actions=["claim_hidden_knowledge", "change_operational_truth_silently"],
        ),
        AIFunction.PORTFOLIO_COPILOT: AIFunctionContract(
            function=AIFunction.PORTFOLIO_COPILOT,
            purpose="Reason over cross-venue patterns, shared gaps, and transferable interventions.",
            risk_level=AIRiskLevel.HIGH,
            output_mode=AIOutputMode.CONVERSATIONAL,
            context_sources=[
                AIContextSource.PORTFOLIO_STATE,
                AIContextSource.SIGNAL_STATE,
                AIContextSource.PLAN_STATE,
                AIContextSource.BLOCK_LIBRARY,
                AIContextSource.OUTCOME_HISTORY,
            ],
            requires_user_confirmation=True,
            system_prompt_version="v1",
            allowed_actions=["identify_system_gaps", "compare_venues", "suggest_transferable_patterns"],
            prohibited_actions=["collapse_venue_specific_context", "hide_confidence_or_tradeoffs"],
        ),
        AIFunction.PROACTIVE_GREETING: AIFunctionContract(
            function=AIFunction.PROACTIVE_GREETING,
            purpose="Offer short, warm, context-aware observations when the operator opens the workspace.",
            risk_level=AIRiskLevel.LOW,
            output_mode=AIOutputMode.CONVERSATIONAL,
            context_sources=[AIContextSource.PORTFOLIO_STATE, AIContextSource.PLAN_STATE],
            requires_user_confirmation=False,
            system_prompt_version="v1",
            allowed_actions=["share_observation", "acknowledge_progress"],
            prohibited_actions=["start_with_action_dump", "pretend_to_have_new_evidence"],
        ),
        AIFunction.REPORT_GENERATION: AIFunctionContract(
            function=AIFunction.REPORT_GENERATION,
            purpose="Turn deterministic diagnostic output into a narrative report without altering the causal chain.",
            risk_level=AIRiskLevel.MEDIUM,
            output_mode=AIOutputMode.NARRATIVE_MARKDOWN,
            context_sources=[AIContextSource.ONTOLOGY, AIContextSource.SIGNAL_STATE, AIContextSource.PLAN_STATE],
            requires_user_confirmation=False,
            system_prompt_version="v1",
            allowed_actions=["summarize_diagnostic_spine", "write_investigation_threads", "write_verification_briefs"],
            prohibited_actions=["change_scores", "change_selected_blocks"],
        ),
        AIFunction.SIGNAL_UPDATE_SUGGESTION: AIFunctionContract(
            function=AIFunction.SIGNAL_UPDATE_SUGGESTION,
            purpose="Propose signal-state additions or removals as structured suggestions inside copilot conversations.",
            risk_level=AIRiskLevel.HIGH,
            output_mode=AIOutputMode.JSON_EMBEDDED_MARKDOWN,
            context_sources=[AIContextSource.VENUE_STATE, AIContextSource.SIGNAL_STATE, AIContextSource.THREAD_HISTORY],
            allows_state_mutation=True,
            requires_user_confirmation=True,
            requires_structured_output=True,
            system_prompt_version="v1",
            allowed_actions=["propose_signal_additions", "propose_signal_removals", "attach_reasoning"],
            prohibited_actions=["apply_signal_mutations_automatically", "emit_unparseable_update_payloads"],
        ),
        AIFunction.ONTOLOGY_EVOLUTION: AIFunctionContract(
            function=AIFunction.ONTOLOGY_EVOLUTION,
            purpose="Suggest ontology additions, mapping changes, or sequencing refinements from accumulated evidence and outcomes.",
            risk_level=AIRiskLevel.CRITICAL,
            output_mode=AIOutputMode.STRUCTURED_JSON,
            context_sources=[
                AIContextSource.ONTOLOGY,
                AIContextSource.EXECUTION_HISTORY,
                AIContextSource.OUTCOME_HISTORY,
                AIContextSource.KNOWLEDGE_BASE,
            ],
            allows_state_mutation=True,
            requires_user_confirmation=True,
            requires_structured_output=True,
            system_prompt_version="v1",
            allowed_actions=["propose_new_signals", "propose_new_mappings", "flag_sequence_gaps"],
            prohibited_actions=["publish_ontology_without_review", "overwrite_existing_truth_without_audit"],
        ),
    }
