"""kb_reading_states and systemic_flags tables

Revision ID: 0b0e456a756e
Revises: 1fc09c34438b
Create Date: 2026-03-29 09:44:18.276785
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0b0e456a756e'
down_revision = '1fc09c34438b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_reading_states',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bookmarked_ids', sa.JSON(), nullable=False),
    sa.Column('read_ids', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('struggles', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('systemic_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('signal_name', sa.String(length=255), nullable=True),
    sa.Column('flagged_by', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flagged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systemic_flags_signal_id'), 'systemic_flags', ['signal_id'], unique=False)
    op.create_index(op.f('ix_systemic_flags_venue_id'), 'systemic_flags', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_systemic_flags_venue_id'), table_name='systemic_flags')
    op.drop_index(op.f('ix_systemic_flags_signal_id'), table_name='systemic_flags')
    op.drop_table('systemic_flags')
    op.drop_table('kb_reading_states')
    # ### end Alembic commands ###

