// Generated by scripts/phase2_contract_freeze.py

export type Vertical = "restaurant" | "cafe" | "hospitality";

export type VenueStatus = "active" | "monitoring" | "paused" | "critical" | "archived";

export type AssessmentKind = "full_diagnostic" | "follow-up" | "weekly_pulse" | "preopening" | "manual_composite";

export type ConfidenceBand = "low" | "medium" | "high" | "critical";

export type PlanStatus = "draft" | "active" | "archived";

export type TaskStatus = "not_started" | "in_progress" | "completed" | "blocked" | "on_hold" | "deferred";

export type DependencyKind = "finish_to_start" | "soft_prerequisite" | "parallel_support";

export type TaskEventType = "status_changed" | "comment_added" | "deliverable_checked" | "sub_action_checked" | "follow_up_created" | "escalated" | "note_captured";

export type CommentVisibility = "internal" | "shared" | "owner";

export type ProgressEntryType = "note" | "update" | "milestone" | "risk" | "decision";

export type ObservationType = "audit_note" | "customer_feedback" | "staff_feedback" | "consultant_observation" | "operational_incident";

export type HelpRequestStatus = "open" | "answered" | "closed";

export type FollowUpStatus = "pending" | "acknowledged" | "completed" | "overdue" | "escalated";

export type EscalationSeverity = "low" | "medium" | "high" | "critical";

export type EscalationStatus = "open" | "acknowledged" | "resolved";

export type NotificationChannel = "web_push" | "email" | "in_app" | "sms";

export type NotificationLevel = "info" | "warning" | "critical";

export type ThreadScope = "global" | "venue" | "task" | "help_request";

export type MessageAuthorRole = "user" | "assistant" | "system";

export type KnowledgeEntityKind = "signal" | "failure_mode" | "response_pattern" | "block" | "tool" | "help_article" | "reference";

export type ReportKind = "diagnostic" | "ai" | "execution";

export type AIFunction = "signal_intake" | "report_generation" | "venue_copilot" | "portfolio_copilot" | "proactive_greeting" | "signal_update_suggestion";

export type AIContextSource = "raw_text_input" | "signal_library" | "ontology" | "venue_state" | "thread_history" | "file_uploads" | "plan_state" | "execution_history";

export type OrganizationContract = {
  id: string;
  name: string;
  slug: string;
  data_residency: string;
};

export type WorkspaceContract = {
  id: string;
  organization_id: string;
  name: string;
  slug: string;
  vertical: Vertical;
  venue_ids?: string[];
};

export type VenueContextContract = {
  venue_name?: string | null;
  venue_type?: string | null;
  team_size?: number | null;
  location?: string | null;
  stage?: string | null;
  concept?: string | null;
};

export type VenueProjectContract = {
  id: string;
  organization_id?: string | null;
  slug: string;
  name: string;
  vertical?: Vertical;
  status?: VenueStatus;
  stage?: string | null;
  concept?: string | null;
  location?: string | null;
  team_size?: number | null;
  capacity_profile?: Record<string, string>;
  workflow_stage?: string | null;
  health_state?: string | null;
  owner_user_id?: string | null;
  primary_consultant_user_id?: string | null;
  next_review_at?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
};

export type AssessmentSignalState = {
  active?: boolean;
  notes?: string | null;
  confidence?: ConfidenceBand | null;
  value?: string | null;
};

export type AssessmentDraftContract = {
  id?: string | null;
  venue_id: string;
  assessment_type: AssessmentKind;
  assessment_date?: string | null;
  created_by?: string | null;
  notes?: string | null;
  selected_signal_ids?: string[];
  signal_states?: Record<string, AssessmentSignalState>;
  raw_input_text?: string | null;
  ontology_version?: string | null;
  management_hours_available?: number;
  weekly_effort_budget?: number;
  venue_context?: VenueContextContract | null;
  created_at?: string | null;
};

export type AssessmentRunRequestContract = {
  venue_id: string;
  assessment_type: AssessmentKind;
  assessment_date?: string | null;
  created_by?: string | null;
  notes?: string | null;
  selected_signal_ids?: string[];
  signal_states?: Record<string, AssessmentSignalState>;
  raw_input_text?: string | null;
  ontology_version?: string | null;
  management_hours_available?: number;
  weekly_effort_budget?: number;
  venue_context?: VenueContextContract | null;
  triage_enabled?: boolean;
  triage_intensity?: string;
};

export type SignalContract = {
  signal_id: string;
  signal_name?: string | null;
  domain_id?: string | null;
  severity?: string | null;
  timestamp?: string | null;
  source_type?: string | null;
  venue_id?: string | null;
  notes?: string | null;
  description?: string | null;
  value?: string | null;
  score?: number | null;
  evidence_snippet?: string | null;
  match_reasons?: string[];
};

export type FailureModeContract = {
  failure_mode_id: string;
  title: string;
  description: string;
  severity: string;
  score: number;
  domain_id?: string | null;
  module_id?: string | null;
  signal_ids?: string[];
};

export type ResponsePatternTriggerContract = {
  failure_mode_id: string;
  fm_title: string;
  fm_score: number;
  link_priority: string;
};

export type ResponsePatternContract = {
  response_pattern_id: string;
  rp_name: string;
  domain?: string | null;
  severity?: string | null;
  priority_score: number;
  description?: string | null;
  triggering_fms?: ResponsePatternTriggerContract[];
  l1_focus?: string | null;
  l2_focus?: string | null;
  l3_focus?: string | null;
};

export type BlockActivationLevelsContract = {
  L1?: string[];
  L2?: string[];
  L3?: string[];
};

export type BlockActivationContract = {
  response_pattern_id: string;
  rp_name: string;
  priority_score?: number | null;
  activated_items: BlockActivationLevelsContract;
};

export type TaskDependencyContract = {
  predecessor_task_id: string;
  successor_task_id: string;
  dependency_kind?: DependencyKind;
  note?: string | null;
};

export type TaskCommentContract = {
  id: string;
  task_id: string;
  venue_id: string;
  author_user_id?: string | null;
  author_name?: string | null;
  body: string;
  visibility?: CommentVisibility;
  created_at: string;
};

export type TaskEventContract = {
  id: string;
  task_id: string;
  event_type: TaskEventType;
  status?: TaskStatus | null;
  actor_user_id?: string | null;
  actor_name?: string | null;
  note?: string | null;
  created_at: string;
};

export type SubActionContract = {
  id?: string | null;
  text: string;
  completed?: boolean;
  completed_at?: string | null;
};

export type DeliverableItemContract = {
  name: string;
  completed?: boolean;
  completed_at?: string | null;
};

export type DeliverableProofContract = {
  id: string;
  task_id?: string | null;
  deliverable_name: string;
  proof_kind: string;
  file_asset_id?: string | null;
  source_url?: string | null;
  note?: string | null;
  created_at: string;
  verified_at?: string | null;
};

export type TaskContract = {
  id: string;
  block_id: string;
  title: string;
  status?: TaskStatus;
  order_index?: number | null;
  layer?: string | null;
  timeline_label?: string | null;
  priority?: string | null;
  effort_hours?: number | null;
  rationale?: string | null;
  description?: string | null;
  notes?: string | null;
  source_response_pattern_id?: string | null;
  source_response_pattern_name?: string | null;
  module_id?: string | null;
  dependency_ids?: string[];
  depends_on_modules?: string[];
  trace?: Record<string, unknown>;
  sub_actions?: SubActionContract[];
  deliverables?: DeliverableItemContract[];
  comments?: TaskCommentContract[];
  events?: TaskEventContract[];
  assigned_to?: string | null;
  assignee_user_id?: string | null;
  assignee_name?: string | null;
  due_at?: string | null;
  created_at?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  updated_at?: string | null;
  updated_by?: string | null;
  review_required?: boolean | null;
  verification?: string | null;
  expected_output?: string | null;
  flags?: string[];
};

export type GeneratedPlanTaskContract = {
  task_id: string;
  item_id: string;
  item_type: string;
  title: string;
  source_rp?: string | null;
  rp_name?: string | null;
  module_id?: string | null;
  timeline?: string | null;
  priority?: string | null;
  description?: string | null;
  depends_on_modules?: string[];
  trace?: Record<string, unknown>;
};

export type GeneratedPlanContract = {
  L1_tasks?: GeneratedPlanTaskContract[];
  L2_tasks?: GeneratedPlanTaskContract[];
  L3_tasks?: GeneratedPlanTaskContract[];
};

export type PlanContract = {
  id: string;
  venue_id: string;
  engine_run_id?: string | null;
  title: string;
  summary: string;
  total_effort_hours?: number | null;
  status?: PlanStatus;
  load_classification?: string | null;
  source_assessment?: string | null;
  version?: number | null;
  previous_versions?: string[];
  owner_user_id?: string | null;
  reviewer_user_id?: string | null;
  approval_requested_at?: string | null;
  approved_at?: string | null;
  approved_by_user_id?: string | null;
  confidence?: Record<string, unknown>;
  strengths?: string[];
  summary_snapshot?: Record<string, unknown>;
  dependency_notes?: string[];
  tasks?: TaskContract[];
  created_at?: string | null;
  updated_at?: string | null;
};

export type ReportContract = {
  id?: string | null;
  engine_run_id?: string | null;
  venue_id: string;
  report_kind: ReportKind;
  report_type: string;
  summary?: string | null;
  markdown: string;
  diagnostic_spine?: string[];
  investigation_threads?: string[];
  verification_briefs?: string[];
  created_at?: string | null;
};

export type DiagnosticResultContract = {
  engine_run_id?: string | null;
  assessment_id?: string | null;
  venue_id: string;
  ontology_version?: string | null;
  load_classification?: string | null;
  normalized_signals?: SignalContract[];
  failure_modes?: FailureModeContract[];
  response_patterns?: ResponsePatternContract[];
  block_activations?: BlockActivationContract[];
  constrained_block_activations?: BlockActivationContract[];
  constraint_report?: Record<string, unknown>;
  generated_plan?: GeneratedPlanContract | null;
  plan?: PlanContract | null;
  report?: ReportContract | null;
};

export type ProgressEntryContract = {
  id: string;
  venue_id: string;
  created_by?: string | null;
  entry_type: ProgressEntryType;
  summary: string;
  detail?: string | null;
  status?: VenueStatus;
  created_at: string;
};

export type ObservationContract = {
  id: string;
  venue_id: string;
  related_task_id?: string | null;
  author_user_id?: string | null;
  observation_type: ObservationType;
  title: string;
  detail: string;
  source: string;
  created_at: string;
  evidence_file_asset_id?: string | null;
};

export type HelpRequestContract = {
  id: string;
  venue_id: string;
  requester_user_id?: string | null;
  channel: string;
  title: string;
  prompt: string;
  status?: HelpRequestStatus;
  linked_thread_id?: string | null;
  created_at: string;
  resolved_at?: string | null;
};

export type FollowUpContract = {
  id: string;
  venue_id: string;
  task_id: string;
  assigned_to?: string | null;
  created_by?: string | null;
  title: string;
  status?: FollowUpStatus;
  due_at: string;
  acknowledged_at?: string | null;
  completed_at?: string | null;
  escalated_at?: string | null;
  notes?: string | null;
  created_at: string;
  is_overdue?: boolean;
};

export type EscalationContract = {
  id: string;
  venue_id: string;
  follow_up_id?: string | null;
  task_id?: string | null;
  created_by?: string | null;
  escalated_to?: string | null;
  severity?: EscalationSeverity;
  status?: EscalationStatus;
  reason: string;
  resolution_notes?: string | null;
  created_at: string;
  resolved_at?: string | null;
};

export type NotificationSubscriptionContract = {
  endpoint: string;
  p256dh_key: string;
  auth_key: string;
  user_id?: string | null;
  channel?: NotificationChannel;
  created_at?: string | null;
};

export type NotificationEventContract = {
  id: string;
  organization_id?: string | null;
  venue_id?: string | null;
  user_id: string;
  channel: NotificationChannel;
  level: NotificationLevel;
  title: string;
  body: string;
  entity_type?: string | null;
  entity_id?: string | null;
  sent_at?: string | null;
  read_at?: string | null;
  acknowledged_at?: string | null;
};

export type ChatReferenceContract = {
  type: string;
  label: string;
  id?: string | null;
  payload?: Record<string, unknown> | null;
};

export type ChatAttachmentContract = {
  file_asset_id?: string | null;
  file_name: string;
  content_type?: string | null;
  url?: string | null;
  content_base64?: string | null;
};

export type ChatMessageContract = {
  id: string;
  thread_id: string;
  created_by?: string | null;
  author_role: MessageAuthorRole;
  source_mode: string;
  content: string;
  references?: ChatReferenceContract[];
  attachments?: ChatAttachmentContract[];
  created_at: string;
};

export type ChatThreadContract = {
  id: string;
  organization_id?: string | null;
  venue_id?: string | null;
  title: string;
  scope: ThreadScope;
  archived?: boolean;
  message_count?: number;
  latest_message_at?: string | null;
  created_at: string;
  messages?: ChatMessageContract[];
};

export type KnowledgeReferenceContract = {
  id: string;
  entity_kind: KnowledgeEntityKind;
  title: string;
  description?: string | null;
  source_ref?: string | null;
  linked_entity_ids?: string[];
  uri?: string | null;
  updated_at?: string | null;
};

export type AITraceContract = {
  function: AIFunction;
  provider: string;
  model: string;
  prompt_version: string;
  invoked_at: string;
  organization_id?: string | null;
  venue_id?: string | null;
  thread_id?: string | null;
  ontology_version?: string | null;
  context_sources?: AIContextSource[];
  evidence_refs?: string[];
  confidence?: ConfidenceBand | null;
  mutation_summary?: Record<string, unknown>;
  user_confirmation_required?: boolean;
  user_confirmation_status?: string | null;
};

export type AIIntakeSnapshotContract = {
  raw_input_text: string;
  raw_input_length?: number | null;
  extraction_summary?: Record<string, unknown>;
  confidence_distribution?: Record<string, number>;
  unmapped_observations?: Record<string, unknown>[];
  active_signal_ids?: string[];
  venue_context?: VenueContextContract | null;
  provider?: string | null;
  model?: string | null;
  prompt_version?: string | null;
};

export type TaskMutationRequestContract = {
  status?: TaskStatus | null;
  notes?: string | null;
  sub_action_completions?: boolean[] | null;
  deliverable_completions?: boolean[] | null;
};

export type CommentCreateRequestContract = {
  task_id: string;
  venue_id: string;
  body: string;
  visibility?: CommentVisibility;
};

export type ProgressCreateRequestContract = {
  venue_id: string;
  entry_type: ProgressEntryType;
  summary: string;
  detail?: string | null;
  status?: VenueStatus;
};

export type FollowUpCreateRequestContract = {
  venue_id: string;
  task_id: string;
  assigned_to?: string | null;
  title: string;
  due_at: string;
  notes?: string | null;
};

export type EscalationCreateRequestContract = {
  venue_id: string;
  follow_up_id?: string | null;
  task_id?: string | null;
  escalated_to?: string | null;
  severity?: EscalationSeverity;
  reason: string;
};

export type ChatMessageCreateRequestContract = {
  content: string;
  created_by?: string | null;
  attachments?: ChatAttachmentContract[];
};
