import json, os
base_path = r"C:\Users\matas\Documents\00 vOIS 3+4 Merge\OIS_Cafe\01_ontology\blocks"
ALL_8 = ["independent_cafe", "specialty_coffee", "chain_cafe", "franchise_cafe", "drive_through", "kiosk", "coffee_van", "bakery_cafe"]
def wb(block):
    path = os.path.join(base_path, block["block_id"] + ".json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(block, f, indent=2, ensure_ascii=False)
    print(block["block_id"] + " written")

wb({
  "block_id": "B183",
  "name": "Health & Safety Risk Assessment",
  "version": "v1.0",
  "domain": "D12_culture_identity",
  "module": "M16: Regulatory Governance & Risk Management",
  "state": "enriched",
  "purpose": "Delivers a comprehensive workplace risk assessment covering all hazards present in a cafe environment \u2014 from scalding steam wands and slippery floors to manual handling of deliveries and repetitive strain from tamping. This block ensures legal compliance with the Health and Safety at Work etc. Act 1974 and the Management of Health and Safety at Work Regulations 1999, while building a proactive safety culture that protects staff, customers, and the business.",
  "purpose_extended": {
    "detailed_objectives": [
      "Conduct a full hazard identification survey covering every area of the cafe: front of house, bar, kitchen, storage, toilets, and exterior",
      "Assess each hazard for likelihood and severity to determine risk rating",
      "Document control measures for every identified risk, assigning responsibility and review dates",
      "Create a living risk assessment document that is reviewed and updated at least annually or when circumstances change",
      "Ensure all staff are briefed on relevant risks and control measures during induction and at regular intervals"
    ],
    "secondary_objectives": [
      "Reduce workplace accidents and near-misses through proactive hazard management",
      "Minimise employer liability and insurance costs through documented due diligence",
      "Build staff confidence by demonstrating that their safety is taken seriously",
      "Create a foundation for fire safety (B184), licensing (B185), and compliance culture (B186) blocks"
    ]
  },
  "why_this_matters": "Under the Health and Safety at Work etc. Act 1974, every employer has a legal duty to ensure, so far as is reasonably practicable, the health, safety, and welfare of all employees. The Management of Health and Safety at Work Regulations 1999 require every employer with five or more employees to conduct and record a suitable and sufficient risk assessment. Even cafes with fewer than five employees must conduct a risk assessment \u2014 they simply are not required to record it in writing, although best practice strongly recommends doing so. The Health and Safety Executive (HSE) can inspect any workplace at any time, and a cafe without a documented risk assessment faces enforcement action ranging from an Improvement Notice to prosecution. In the hospitality sector, the most common hazards include burns and scalds (from steam wands, hot water, and cooking equipment), slips, trips and falls (wet floors, cables, uneven surfaces), manual handling injuries (lifting deliveries, moving furniture), cuts (from knives, broken crockery), and electrical hazards (faulty equipment, overloaded sockets). A single workplace accident can result in HSE investigation, potential prosecution, personal injury claims, increased insurance premiums, loss of key staff to injury, and reputational damage. For a small cafe, a successful personal injury claim or HSE prosecution can be financially devastating.",
  "application_logic": {
    "L1": "IMMEDIATE (0\u20132 weeks). Week 1: Download the HSE risk assessment template (available free from hse.gov.uk) or use the template provided in T183-01. Walk through every area of the cafe with a notebook: bar area, kitchen/prep, storage, customer seating, toilets, entrance/exit, and any outdoor areas. For each area, list every hazard you can identify \u2014 hot surfaces, sharp objects, wet floors, heavy items at height, electrical equipment, trip hazards, chemical cleaning products. For each hazard, note who might be harmed, how, and what controls are already in place. Rate each risk as high, medium, or low. Week 2: For each medium and high risk, document specific control measures: what needs to be done, who is responsible, and by when. Post a summary of key risks and controls in the staff area. Brief all current staff on the risk assessment findings. File the completed risk assessment and note the review date.",
    "L2": "SYSTEM BUILD (2\u20138 weeks). Develop a Health and Safety SOP library covering the top risks: burns and scalds prevention, manual handling technique, slip prevention and wet floor procedures, chemical handling (COSHH), and electrical safety. Introduce a near-miss reporting system \u2014 a simple form where staff can record incidents that nearly caused harm. Near-miss data is invaluable for identifying emerging risks before they cause harm. Conduct specific risk assessments for vulnerable groups: pregnant workers, young workers (under 18), and anyone with a disability. Review insurance policies to ensure coverage aligns with identified risks. Schedule quarterly risk assessment reviews. Train a designated member of staff as the health and safety lead.",
    "L3": "CULTURE & EXCELLENCE (8+ weeks). Integrate risk assessment into daily operations through pre-shift safety checks. Establish a health and safety committee that meets quarterly to review risks, near-misses, and improvement ideas. Conduct annual external health and safety audits. Benchmark accident rates against industry data from HSE hospitality statistics. Invest in additional controls for persistent risks: anti-fatigue mats, burn-resistant gloves, automatic wet floor signs, cable management solutions. Develop a culture where any team member can raise a safety concern without hesitation."
  },
  "execution_framework": {
    "L1_setup": {"title": "Immediate Actions", "actions": ["Download or create a risk assessment template suitable for cafe environments", "Conduct a full hazard identification walk-through of every area of the premises", "Rate each identified hazard for likelihood and severity", "Document control measures for every medium and high risk with assigned responsibility", "Brief all staff on key risks and control measures in a team meeting", "File the completed risk assessment and set an annual review date", "Ensure the accident book (BI 510) is available and all staff know where it is"], "responsible": "Cafe Owner, Manager"},
    "L2_build": {"title": "System Development", "actions": ["Develop Health and Safety SOPs for top risk categories", "Introduce a near-miss reporting system", "Conduct specific risk assessments for vulnerable groups", "Review insurance coverage against identified risks", "Schedule quarterly risk assessment reviews", "Designate and train a health and safety lead", "Create a COSHH register for all cleaning chemicals and hazardous substances"], "responsible": "Manager, Health & Safety Lead"},
    "L3_embed": {"title": "Culture Embedding", "actions": ["Integrate pre-shift safety checks into daily opening routines", "Establish a quarterly health and safety review meeting", "Conduct annual external health and safety audits", "Benchmark accident rates against HSE hospitality industry data", "Invest in additional physical controls for persistent risk areas", "Build a culture where near-miss reporting is encouraged and celebrated"], "responsible": "Owner, Manager, Health & Safety Lead"}
  },
  "deliverables": ["Comprehensive Risk Assessment document (cafe-specific template)", "Health and Safety SOP library", "Near-Miss Reporting Form", "COSHH Register template", "Quarterly Risk Review template"],
  "embedded_tools": [],
  "tool_definitions": {"tools": [
    {"tool_id": "T183-01", "tool_name": "Cafe Risk Assessment Template", "level": "L1", "format": "template", "owner_role": "Owner", "description": "Comprehensive risk assessment template pre-populated with common cafe hazards organised by area (bar, kitchen, storage, customer area, exterior), with columns for hazard, who is at risk, existing controls, risk rating, additional controls needed, responsible person, and review date."},
    {"tool_id": "T183-02", "tool_name": "Near-Miss Reporting Form", "level": "L2", "format": "checklist", "owner_role": "All Staff", "description": "Simple one-page form for recording near-miss incidents: date, time, location, description of what happened, what prevented harm, and suggested improvement. Anonymity option included to encourage reporting."},
    {"tool_id": "T183-03", "tool_name": "Health and Safety SOP Library Index", "level": "L2", "format": "SOP", "owner_role": "Manager", "description": "Master index of all health and safety SOPs covering burns prevention, manual handling, slip prevention, COSHH, electrical safety, and lone working, with version control and review schedule."},
    {"tool_id": "T183-04", "tool_name": "COSHH Assessment Register", "level": "L2", "format": "tracker", "owner_role": "Manager", "description": "Register of all hazardous substances used in the cafe (cleaning chemicals, descalers, sanitisers) with safety data sheets, storage requirements, PPE requirements, and first aid measures."},
    {"tool_id": "T183-05", "tool_name": "Quarterly Risk Review Checklist", "level": "L3", "format": "checklist", "owner_role": "Owner", "description": "Quarterly review checklist covering all risk assessment entries, near-miss trends, accident book review, control measure effectiveness, and actions arising. Signed off by owner."}
  ]},
  "failure_modes": ["Risk assessment is completed once and never reviewed, becoming outdated as the cafe changes equipment, layout, or activities", "Risk assessment is a paper exercise that does not translate into actual workplace practices or staff awareness", "Near-misses go unreported because staff fear blame, allowing hazards to persist until a serious accident occurs", "Control measures are documented but not implemented or enforced, creating a false sense of security"],
  "kpis": ["Risk assessment completed and documented with zero overdue review dates", "All staff briefed on relevant risks within one week of starting employment", "Near-miss reports submitted at a rate indicating genuine engagement (minimum 1 per quarter per 5 staff)", "Zero HSE enforcement notices or improvement orders"],
  "dependencies": ["B184"],
  "constraints": ["Employers with 5 or more employees must record the risk assessment in writing", "Risk assessment must be reviewed at least annually or whenever there is a significant change", "An accident book (BI 510) must be maintained and RIDDOR-reportable incidents reported within statutory timescales"],
  "time_load": {"L1": "4 hours (initial walk-through, documentation, staff briefing)", "L2": "8 hours (SOP development, COSHH register, near-miss system setup)", "L3": "2 hours/quarter (reviews, audits, updates)"},
  "review_protocol": "Annual full review of risk assessment document. Quarterly review of near-miss reports and accident book. Immediate review after any accident, near-miss involving injury, or significant change to premises or equipment. Staff briefing whenever risk assessment is updated.",
  "meta": {"summary_for_humans": "This block delivers a comprehensive workplace risk assessment covering all cafe hazards, with documented control measures, near-miss reporting, and a structured review cycle.", "implementation_risks": ["Owner may underestimate the breadth of hazards in a cafe environment", "Risk assessment can feel bureaucratic for small teams \u2014 keep it practical and cafe-specific", "Without near-miss reporting, the risk assessment only captures known hazards, not emerging ones"], "notes_for_engine": "Foundation block for the regulatory governance module. Activate before or alongside B184 (fire safety) and B185 (licensing). Flag urgently if signals indicate workplace accidents, HSE visits, or missing documentation.", "tags": ["health_safety", "risk_assessment", "HSE", "compliance", "COSHH", "workplace_safety", "regulatory"]},
  "applicability": {"venue_types": ALL_8, "team_size_min": 1, "team_size_max": 99},
  "enrichment_status": {"level": "gold", "enriched_at": "2026-03-04T12:00:00Z", "enriched_by": "claude_direct_v2", "source_quality": "ai_generated"}
})

wb({
  "block_id": "B184",
  "name": "Fire Safety & Emergency Procedures",
  "version": "v1.0",
  "domain": "D12_culture_identity",
  "module": "M16: Regulatory Governance & Risk Management",
  "state": "enriched",
  "purpose": "Ensures full compliance with the Regulatory Reform (Fire Safety) Order 2005 by establishing a documented fire risk assessment, emergency evacuation procedures, staff training, and equipment maintenance schedules. This block protects lives, preserves the premises, and prevents the catastrophic business impact of a fire incident or enforcement action.",
  "purpose_extended": {
    "detailed_objectives": [
      "Complete a fire risk assessment specific to the cafe premises identifying all ignition sources, fuel sources, and people at risk",
      "Establish clear emergency evacuation procedures with designated assembly points and roles",
      "Ensure all fire safety equipment (extinguishers, blankets, alarms, emergency lighting) is in place, tested, and maintained",
      "Train all staff on fire prevention, evacuation procedures, and use of fire-fighting equipment",
      "Maintain a fire safety log book documenting all tests, drills, and maintenance activities"
    ],
    "secondary_objectives": [
      "Satisfy requirements for premises licence conditions relating to fire safety",
      "Reduce insurance premiums through demonstrable fire risk management",
      "Build staff confidence in emergency response through regular drills",
      "Coordinate with the local fire and rescue service on compliance requirements"
    ]
  },
  "why_this_matters": "The Regulatory Reform (Fire Safety) Order 2005 places full responsibility for fire safety on the responsible person \u2014 in most cafes, this is the owner or operator. Failure to comply is a criminal offence carrying penalties of unlimited fines and up to two years in prison. Following the Grenfell Tower tragedy and subsequent Fire Safety Act 2021, enforcement has tightened significantly. A cafe presents multiple fire risks: gas cookers and ovens, electrical equipment (grinders, dishwashers, EPOS systems), overloaded sockets, flammable cleaning chemicals, paper and cardboard storage, and extraction systems that accumulate grease. Beyond the risk to life, a fire can destroy a business entirely \u2014 even a small fire causing smoke damage can close a cafe for weeks or months, and insurance may not cover the full loss if fire safety obligations were not met. The fire risk assessment is the cornerstone document that demonstrates compliance.",
  "application_logic": {
    "L1": "IMMEDIATE (0\u20132 weeks). Week 1: Obtain a fire risk assessment template appropriate for small commercial premises or use T184-01. Walk through the premises identifying: all ignition sources (ovens, grills, toasters, electrical equipment, smoking areas), all fuel sources (paper, cardboard, cooking oils, cleaning chemicals, soft furnishings), and all people at risk. Check that fire alarm system or manual call points, fire extinguishers (minimum one water or foam, one CO2, plus a fire blanket in any cooking area), emergency lighting, illuminated fire exit signs, and clear escape routes are all in place and functional. Week 2: Draft emergency evacuation procedures: who raises the alarm, who calls 999, who checks toilets and back areas, where the assembly point is, who takes the roll call. Post the evacuation procedure and floor plan showing exits and extinguisher locations. Brief all staff and conduct a walk-through of escape routes.",
    "L2": "SYSTEM BUILD (2\u20138 weeks). Complete the full fire risk assessment document and file it on the premises. Establish a fire safety log book recording: weekly fire alarm tests, monthly emergency lighting checks, annual fire extinguisher servicing, six-monthly fire drill records, and any fire safety issues identified and resolved. Train all staff on fire extinguisher use. Register for a free business fire safety visit from the local fire and rescue service. Review PAT testing compliance and EICR validity. Ensure extraction systems and filters are cleaned regularly to prevent grease accumulation.",
    "L3": "CULTURE & EXCELLENCE (8+ weeks). Conduct fire drills at least every six months, varying the scenario. Debrief after each drill and document learnings. Install additional fire prevention measures where appropriate: automatic fire suppression in extraction hoods, heat detectors in kitchen areas, linked fire alarm systems. Review the fire risk assessment annually or whenever there is a significant change. Ensure fire safety is part of every new staff induction from day one."
  },
  "execution_framework": {
    "L1_setup": {"title": "Immediate Actions", "actions": ["Obtain a fire risk assessment template and begin the premises walk-through", "Verify all fire safety equipment is present, functional, and correctly positioned", "Install any missing fire extinguishers, fire blankets, or emergency signage", "Draft emergency evacuation procedures with roles and assembly point", "Post evacuation procedure and floor plan in visible locations", "Brief all staff on evacuation procedure and conduct an escape route walk-through", "Ensure all escape routes are clear and unobstructed"], "responsible": "Cafe Owner"},
    "L2_build": {"title": "System Development", "actions": ["Complete and file the full fire risk assessment document", "Establish a fire safety log book with weekly, monthly, and annual check schedules", "Train all staff on fire extinguisher use and fire prevention", "Arrange annual fire extinguisher servicing with a certified provider", "Register for a local fire and rescue service business fire safety visit", "Verify PAT testing and EICR compliance for all electrical systems", "Schedule regular extraction system and filter cleaning"], "responsible": "Owner, Manager"},
    "L3_embed": {"title": "Culture Embedding", "actions": ["Conduct fire drills at least every six months with varied scenarios and debriefs", "Evaluate additional fire prevention technology (suppression systems, linked alarms)", "Review the fire risk assessment annually and after any significant change", "Integrate fire safety into all new staff induction programmes", "Maintain ongoing relationship with local fire and rescue service", "Review business interruption insurance for fire-related closure coverage"], "responsible": "Owner, Manager"}
  },
  "deliverables": ["Fire Risk Assessment document (cafe-specific template)", "Emergency Evacuation Procedure and floor plan", "Fire Safety Log Book template", "Staff Fire Safety Training Record", "Fire Drill Record and Debrief template"],
  "embedded_tools": [],
  "tool_definitions": {"tools": [
    {"tool_id": "T184-01", "tool_name": "Cafe Fire Risk Assessment Template", "level": "L1", "format": "template", "owner_role": "Owner", "description": "Comprehensive fire risk assessment template pre-populated with common cafe fire hazards, covering ignition sources, fuel sources, people at risk, existing controls, and additional measures needed. Aligned with Regulatory Reform (Fire Safety) Order 2005 requirements."},
    {"tool_id": "T184-02", "tool_name": "Emergency Evacuation Procedure Template", "level": "L1", "format": "SOP", "owner_role": "Manager", "description": "Clear A4 evacuation procedure document defining roles (fire warden, caller, sweep), evacuation route, assembly point, and re-entry protocol. Includes a customisable floor plan showing exits and equipment locations."},
    {"tool_id": "T184-03", "tool_name": "Fire Safety Log Book", "level": "L2", "format": "tracker", "owner_role": "Manager", "description": "Structured log book recording weekly alarm tests, monthly emergency lighting checks, annual extinguisher servicing, fire drill records, and any fire safety issues. Provides an auditable compliance trail."},
    {"tool_id": "T184-04", "tool_name": "Staff Fire Safety Training Record", "level": "L2", "format": "checklist", "owner_role": "Manager", "description": "Individual training record documenting each staff member's fire safety induction, extinguisher training, evacuation drill participation, and refresher dates."},
    {"tool_id": "T184-05", "tool_name": "Fire Drill Record and Debrief Template", "level": "L3", "format": "template", "owner_role": "Owner", "description": "Template for recording fire drill date, scenario, evacuation time, issues identified, and corrective actions. Includes a debrief section for capturing lessons learned."}
  ]},
  "failure_modes": ["Fire risk assessment is never completed, leaving the cafe in breach of the law from day one of trading", "Fire safety equipment is installed but never tested or serviced, giving false assurance", "Escape routes become blocked by deliveries, furniture, or stored items without anyone noticing", "Staff have never practised an evacuation and freeze or make dangerous decisions during a real emergency"],
  "kpis": ["Fire risk assessment completed, documented, and reviewed at least annually", "Fire alarm tested weekly with 100% compliance recorded in the log book", "Fire drills conducted at least every six months with documented debriefs", "All fire safety equipment serviced annually by a certified provider"],
  "dependencies": ["B183"],
  "constraints": ["Fire risk assessment must be in writing if the business has 5 or more employees", "Fire extinguishers must be serviced annually by a competent person to BS 5306", "The Regulatory Reform (Fire Safety) Order 2005 makes the responsible person criminally liable for non-compliance"],
  "time_load": {"L1": "3 hours (walk-through, equipment check, evacuation procedure, staff briefing)", "L2": "5 hours (full FRA completion, log book setup, training, servicing arrangement)", "L3": "2 hours/six months (drills, reviews, updates)"},
  "review_protocol": "Weekly fire alarm test. Monthly emergency lighting check. Six-monthly fire drill with debrief. Annual full review of fire risk assessment. Immediate review after any fire incident, near-miss, or significant change to premises.",
  "meta": {"summary_for_humans": "This block ensures full fire safety compliance including a documented fire risk assessment, emergency evacuation procedures, equipment maintenance, staff training, and regular drills.", "implementation_risks": ["Owners of small cafes may assume fire safety rules only apply to larger premises \u2014 they apply to all", "Professional fire risk assessment may be needed if the premises is complex", "Fire safety equipment costs can surprise small operators \u2014 budget accordingly"], "notes_for_engine": "Activate alongside B183 (health and safety risk assessment). Flag urgently if signals indicate no fire risk assessment, overdue equipment servicing, or upcoming fire service inspection.", "tags": ["fire_safety", "emergency", "evacuation", "compliance", "regulatory", "risk_assessment", "fire_risk"]},
  "applicability": {"venue_types": ALL_8, "team_size_min": 1, "team_size_max": 99},
  "enrichment_status": {"level": "gold", "enriched_at": "2026-03-04T12:00:00Z", "enriched_by": "claude_direct_v2", "source_quality": "ai_generated"}
})

wb({
  "block_id": "B185",
  "name": "Licensing & Employment Law Audit",
  "version": "v1.0",
  "domain": "D12_culture_identity",
  "module": "M16: Regulatory Governance & Risk Management",
  "state": "enriched",
  "purpose": "Conducts a thorough audit of all licensing requirements and employment law obligations applicable to the cafe, ensuring compliance with premises licensing, food business registration, music licensing, employment contracts, right-to-work checks, and workplace pensions. This block prevents the legal and financial consequences of operating without proper authorisation or breaching employment law.",
  "purpose_extended": {
    "detailed_objectives": [
      "Audit all premises licensing requirements: food business registration, alcohol licence (if applicable), pavement licence, late-night refreshment licence",
      "Verify compliance with music licensing obligations (PPL PRS) for any background music, radio, or streaming",
      "Review all employment contracts for compliance with the Employment Rights Act 1996 and amendments",
      "Confirm right-to-work checks are completed and documented for every employee",
      "Ensure workplace pension auto-enrolment obligations are met under the Pensions Act 2008"
    ],
    "secondary_objectives": [
      "Identify any licensing gaps that could result in fines, closure, or prosecution",
      "Ensure payslip compliance with the Employment Rights Act 1996 (as amended 2019)",
      "Review working time compliance including rest breaks, maximum hours, and holiday entitlement",
      "Verify that employer liability insurance is current and displayed"
    ]
  },
  "why_this_matters": "A cafe operates under a complex web of licensing and employment law that many owners do not fully understand until they face enforcement action. Every cafe must be registered as a food business with the local authority at least 28 days before opening \u2014 failure to register is a criminal offence. If the cafe plays any background music (including radio or streaming services), it needs both a PPL and PRS licence. If the cafe serves alcohol, a premises licence and a designated premises supervisor with a personal licence are required under the Licensing Act 2003 \u2014 selling alcohol without a licence carries an unlimited fine and up to six months in prison. On the employment side, every employee must receive a written statement of employment particulars on or before their first day of work. Right-to-work checks must be conducted before employment begins \u2014 employing someone without the right to work can result in a civil penalty of up to \u00a345,000 per worker. Workplace pension auto-enrolment is mandatory for all eligible employees. National Minimum Wage and National Living Wage must be paid correctly \u2014 HMRC conducts targeted enforcement and publicly names non-compliant employers.",
  "application_logic": {
    "L1": "IMMEDIATE (0\u20132 weeks). Week 1: Create a licensing and compliance checklist using T185-01. Verify: (1) food business registration with the local authority, (2) food hygiene rating displayed, (3) employer liability insurance certificate displayed, (4) PPL PRS music licence in place if any music is played, (5) pavement licence if tables are placed outside on public land, (6) alcohol premises licence if applicable. For each item, confirm it is in place, note the renewal date, and flag any gaps. Week 2: Review employment law basics. Check that every employee has: (1) a written statement of employment particulars, (2) a completed right-to-work check with copies retained, (3) correct NMW/NLW rate, (4) itemised payslips, (5) auto-enrolment in a workplace pension or a valid opt-out.",
    "L2": "SYSTEM BUILD (2\u20138 weeks). Build a compliance calendar that tracks all renewal dates, filing deadlines, and periodic obligations. Develop template employment contracts that comply with current legislation. Create an employee onboarding checklist that includes right-to-work verification, contract issuance, pension enrolment, and health and safety induction. Review working time compliance: ensure no staff member regularly exceeds 48 hours per week without a signed opt-out, that rest breaks are provided for shifts over 6 hours, and that holiday entitlement is correctly calculated. Ensure the cafe has a basic disciplinary and grievance policy in line with ACAS guidance.",
    "L3": "CULTURE & EXCELLENCE (8+ weeks). Conduct an annual licensing and employment law audit using an external adviser or solicitor specialising in hospitality law. Subscribe to employment law update services to stay ahead of legislative changes. Build compliance awareness into the management team. Review and update employment contracts whenever legislation changes. Maintain a central compliance file containing all licences, insurance certificates, contracts, right-to-work records, and pension correspondence."
  },
  "execution_framework": {
    "L1_setup": {"title": "Immediate Actions", "actions": ["Complete a licensing audit checklist covering all required licences and registrations", "Verify food business registration status with the local authority", "Confirm PPL PRS music licence is in place if any music is played", "Check that employer liability insurance is current and displayed", "Review every employee file for written contract, right-to-work check, and pension enrolment", "Verify NMW/NLW rates are correct for all staff", "Flag and prioritise any compliance gaps for immediate resolution"], "responsible": "Cafe Owner"},
    "L2_build": {"title": "System Development", "actions": ["Build a compliance calendar tracking all renewal dates and deadlines", "Develop template employment contracts compliant with current legislation", "Create an employee onboarding checklist including all legal requirements", "Review and document working time compliance for all staff", "Establish disciplinary and grievance procedures in line with ACAS guidance", "Verify alcohol licensing compliance if applicable", "Set up a central compliance file for all licences and employment records"], "responsible": "Owner, Manager"},
    "L3_embed": {"title": "Culture Embedding", "actions": ["Conduct annual licensing and employment law audits", "Subscribe to employment law update services to track legislative changes", "Build compliance awareness into management team responsibilities", "Review and update employment contracts with each legislative change", "Maintain a comprehensive central compliance file", "Consider membership of a hospitality employers association for ongoing support"], "responsible": "Owner"}
  },
  "deliverables": ["Licensing & Compliance Audit Checklist", "Compliance Calendar with renewal dates and deadlines", "Template Employment Contract (cafe-specific)", "Employee Onboarding Compliance Checklist", "Central Compliance File structure guide"],
  "embedded_tools": [],
  "tool_definitions": {"tools": [
    {"tool_id": "T185-01", "tool_name": "Licensing & Compliance Audit Checklist", "level": "L1", "format": "checklist", "owner_role": "Owner", "description": "Comprehensive checklist covering all licensing and regulatory requirements for a cafe: food business registration, music licensing, alcohol licensing, pavement licence, employer liability insurance, data protection registration, and signage requirements."},
    {"tool_id": "T185-02", "tool_name": "Employment Law Compliance Checklist", "level": "L1", "format": "checklist", "owner_role": "Owner", "description": "Per-employee checklist verifying: written contract issued, right-to-work check completed, correct NMW/NLW rate, itemised payslips, pension auto-enrolment, and working time compliance."},
    {"tool_id": "T185-03", "tool_name": "Compliance Calendar", "level": "L2", "format": "tracker", "owner_role": "Manager", "description": "Annual calendar tracking all licence renewal dates, insurance expiry, pension re-enrolment dates, and regulatory filing deadlines with advance warning alerts."},
    {"tool_id": "T185-04", "tool_name": "Template Employment Contract", "level": "L2", "format": "template", "owner_role": "Owner", "description": "Cafe-specific employment contract template including all mandatory particulars required by the Employment Rights Act 1996 (as amended), customisable for different roles and working patterns."},
    {"tool_id": "T185-05", "tool_name": "Employee Onboarding Compliance Checklist", "level": "L2", "format": "checklist", "owner_role": "Manager", "description": "Step-by-step onboarding checklist ensuring all legal requirements are met before or on day one: right-to-work check, contract issuance, pension information, health and safety briefing, and data protection notice."}
  ]},
  "failure_modes": ["Food business registration lapses or was never completed, making the cafe an unregistered food premises", "Music is played without a PPL PRS licence, resulting in legal action and backdated fees", "Right-to-work checks are not completed before employment begins, exposing the owner to civil penalties up to \u00a345,000 per worker", "Workplace pension auto-enrolment is missed, triggering escalating penalties from the Pensions Regulator"],
  "kpis": ["All required licences and registrations current with zero lapses", "100% of employees have a written contract issued on or before day one", "Right-to-work checks completed and documented for every employee before employment starts", "Workplace pension auto-enrolment obligations met with zero Pensions Regulator notices"],
  "dependencies": ["B183"],
  "constraints": ["Food business registration must be completed at least 28 days before opening", "Employment contracts must be issued on or before the employee's first day of work", "Right-to-work documents must be checked before employment begins \u2014 retrospective checks are not valid"],
  "time_load": {"L1": "4 hours (licensing audit, employment file review, gap identification)", "L2": "8 hours (compliance calendar, contract templates, onboarding checklist, working time review)", "L3": "4 hours/year (annual audit, legislative updates, contract reviews)"},
  "review_protocol": "Monthly check of compliance calendar for upcoming renewals and deadlines. Quarterly review of employee files for completeness. Annual full licensing and employment law audit. Immediate review when legislation changes or new staff are hired.",
  "meta": {"summary_for_humans": "This block audits all licensing requirements and employment law obligations for the cafe, from food business registration and music licensing to employment contracts, right-to-work checks, and pension auto-enrolment.", "implementation_risks": ["Many cafe owners are unaware of music licensing requirements until they receive a demand letter", "Employment law changes frequently \u2014 contracts must be reviewed when legislation updates", "Small cafes often delay pension auto-enrolment, not realising the Pensions Regulator actively enforces compliance"], "notes_for_engine": "Activate alongside B183 (risk assessment). Flag urgently if signals indicate missing licences, employment disputes, or regulatory correspondence.", "tags": ["licensing", "employment_law", "compliance", "contracts", "pensions", "right_to_work", "regulatory", "legal"]},
  "applicability": {"venue_types": ALL_8, "team_size_min": 1, "team_size_max": 99},
  "enrichment_status": {"level": "gold", "enriched_at": "2026-03-04T12:00:00Z", "enriched_by": "claude_direct_v2", "source_quality": "ai_generated"}
})

wb({
  "block_id": "B186",
  "name": "Regulatory Excellence & Compliance Culture",
  "version": "v1.0",
  "domain": "D12_culture_identity",
  "module": "M16: Regulatory Governance & Risk Management",
  "state": "enriched",
  "purpose": "Elevates compliance from a reactive obligation into a proactive competitive advantage by embedding a culture where every team member understands, owns, and champions regulatory standards. This block builds the systems, habits, and mindset that make compliance the default rather than the exception, and positions the cafe as a benchmark for regulatory excellence.",
  "purpose_extended": {
    "detailed_objectives": [
      "Build a compliance culture where regulatory adherence is seen as a point of pride rather than a burden",
      "Create a unified compliance management system integrating health and safety, fire safety, food safety, licensing, and employment law",
      "Establish a compliance champion role within the team for day-to-day regulatory oversight",
      "Develop a self-audit programme that identifies compliance gaps before external inspectors do",
      "Track and celebrate compliance achievements to reinforce positive behaviours"
    ],
    "secondary_objectives": [
      "Reduce the stress and cost of regulatory inspections through proactive preparation",
      "Build customer and community trust by publicly demonstrating compliance excellence",
      "Create a compliance knowledge base that survives staff turnover",
      "Position the cafe as an employer of choice by demonstrating genuine care for legal and ethical standards"
    ]
  },
  "why_this_matters": "Compliance is typically the least exciting topic in cafe management \u2014 until something goes wrong. A failed EHO inspection, a fire service enforcement notice, an HMRC wage audit, or a personal injury claim can each individually threaten the survival of a small business. When multiple compliance gaps exist simultaneously, the cumulative risk is severe. But compliance excellence is not just about avoiding disaster \u2014 it is a genuine competitive advantage. A cafe that consistently achieves a 5-star food hygiene rating, passes fire inspections without issues, and treats its staff lawfully and fairly enjoys benefits beyond legal protection. Customers increasingly check food hygiene ratings. Staff prefer to work in safe, fairly-treated environments. Insurance premiums are lower for well-managed premises. This block sits at the apex of the regulatory governance module, bringing together B183, B184, and B185 into a cohesive culture of excellence.",
  "application_logic": {
    "L1": "IMMEDIATE (0\u20132 weeks). Week 1: Conduct a compliance baseline assessment. Using the outputs from B183, B184, and B185, create a single-page compliance status summary showing the status of health and safety risk assessment, fire risk assessment, food safety documentation, all licences, and employment law compliance. Colour-code each area green, amber, or red. Week 2: Appoint a compliance champion \u2014 the owner, manager, or a senior team member who takes responsibility for maintaining compliance records, tracking renewal dates, and being the first point of contact when a regulatory body visits. Brief the team on the concept of compliance culture. Post the compliance status summary in the staff area.",
    "L2": "SYSTEM BUILD (2\u20138 weeks). Create a unified compliance folder containing all documentation from B183, B184, and B185 in a structured format. Develop a monthly self-audit checklist that the compliance champion completes. Establish a compliance calendar integrating all renewal dates, review dates, and periodic obligations. Create a regulatory visit preparation protocol. Build compliance topics into regular team meetings. Document any compliance failures or near-misses and the corrective actions taken.",
    "L3": "CULTURE & EXCELLENCE (8+ weeks). Conduct quarterly self-audits with the owner or an external adviser reviewing results. Celebrate compliance milestones: consecutive 5-star food hygiene ratings, clean fire inspections, zero HSE notices. Share compliance achievements with customers where appropriate. Build a compliance knowledge base accessible during induction. Benchmark compliance performance against industry standards. Consider obtaining voluntary certifications signalling commitment to excellence. Conduct an annual compliance strategy review."
  },
  "execution_framework": {
    "L1_setup": {"title": "Immediate Actions", "actions": ["Conduct a compliance baseline assessment across all regulatory areas", "Create a single-page compliance status summary with colour-coded ratings", "Appoint a compliance champion with clear responsibilities", "Brief the team on compliance culture and its importance", "Post the compliance status summary in the staff area", "Identify the three most urgent compliance gaps and create a resolution plan", "Ensure the compliance folder location is known to all managers"], "responsible": "Cafe Owner"},
    "L2_build": {"title": "System Development", "actions": ["Create a unified compliance folder with structured sections for each regulatory area", "Develop a monthly self-audit checklist for the compliance champion", "Build an integrated compliance calendar with all renewal and review dates", "Create a regulatory visit preparation protocol", "Integrate compliance topics into regular team meetings", "Document all compliance failures, near-misses, and corrective actions", "Train the compliance champion on all regulatory areas"], "responsible": "Owner, Manager, Compliance Champion"},
    "L3_embed": {"title": "Culture Embedding", "actions": ["Conduct quarterly self-audits with owner or external adviser review", "Celebrate and publicise compliance milestones with the team and customers", "Build a compliance knowledge base accessible during induction", "Benchmark compliance performance against industry standards", "Consider voluntary certifications that demonstrate commitment to excellence", "Conduct an annual compliance strategy review setting improvement targets"], "responsible": "Owner, Compliance Champion"}
  },
  "deliverables": ["Compliance Status Summary (single-page dashboard)", "Unified Compliance Folder structure guide", "Monthly Self-Audit Checklist", "Regulatory Visit Preparation Protocol", "Annual Compliance Strategy Review template"],
  "embedded_tools": [],
  "tool_definitions": {"tools": [
    {"tool_id": "T186-01", "tool_name": "Compliance Status Summary Dashboard", "level": "L1", "format": "dashboard", "owner_role": "Owner", "description": "Single-page visual summary showing compliance status across all regulatory areas with green/amber/red ratings and key dates."},
    {"tool_id": "T186-02", "tool_name": "Compliance Champion Role Description", "level": "L1", "format": "reference", "owner_role": "Owner", "description": "Role description for the compliance champion including responsibilities, time allocation, authority level, and reporting requirements."},
    {"tool_id": "T186-03", "tool_name": "Regulatory Visit Preparation Protocol", "level": "L2", "format": "SOP", "owner_role": "Manager", "description": "Step-by-step protocol for when a regulatory inspector arrives: greeting procedure, documentation to present, areas to show, questions to expect, and post-visit follow-up actions."},
    {"tool_id": "T186-04", "tool_name": "Monthly Self-Audit Checklist", "level": "L2", "format": "checklist", "owner_role": "Compliance Champion", "description": "Comprehensive monthly checklist covering critical compliance items across all regulatory areas, completed by the compliance champion and reviewed by the owner."},
    {"tool_id": "T186-05", "tool_name": "Annual Compliance Strategy Review Template", "level": "L3", "format": "template", "owner_role": "Owner", "description": "Annual review template covering compliance performance, audit results, inspection outcomes, gaps addressed, and improvement targets for the coming year."}
  ]},
  "failure_modes": ["Compliance is seen as the owner's problem alone, with no team engagement or shared responsibility", "The compliance champion role is appointed but not supported with time, training, or authority", "Self-audits become tick-box exercises that do not identify genuine gaps", "Compliance documentation exists but is not kept current, creating a false sense of security"],
  "kpis": ["Compliance status summary shows all areas green for at least 10 months per year", "Monthly self-audit completed every month without exception", "Zero enforcement notices, improvement orders, or prosecution across all regulatory areas", "All regulatory inspections passed at the highest achievable standard"],
  "dependencies": ["B183", "B184", "B185"],
  "constraints": ["Compliance champion must have adequate time allocated (minimum 2 hours per month)", "The unified compliance folder must be accessible on the premises at all times", "Self-audit results must be acted upon \u2014 documenting a gap without resolving it is worse than not documenting it"],
  "time_load": {"L1": "3 hours (baseline assessment, champion appointment, team briefing)", "L2": "6 hours (folder creation, calendar build, protocols, training)", "L3": "3 hours/quarter (self-audits, reviews, strategy updates)"},
  "review_protocol": "Monthly self-audit by compliance champion. Quarterly review of self-audit results by owner. Annual full compliance strategy review. Immediate review after any regulatory inspection or enforcement action.",
  "meta": {"summary_for_humans": "This block elevates compliance from a reactive obligation into a proactive culture of excellence, unifying health and safety, fire, food safety, licensing, and employment law into a single managed system with a dedicated compliance champion.", "implementation_risks": ["Without genuine owner commitment, compliance culture initiatives will be perceived as lip service", "The compliance champion needs real authority and time allocation to be effective", "Over-documenting can create bureaucracy that alienates small teams \u2014 keep systems proportionate"], "notes_for_engine": "Activate after B183, B184, and B185 are substantially complete. This is the capstone block for the regulatory governance module. Flag if signals indicate multiple concurrent compliance gaps.", "tags": ["compliance", "culture", "regulatory", "governance", "self_audit", "compliance_champion", "excellence"]},
  "applicability": {"venue_types": ALL_8, "team_size_min": 1, "team_size_max": 99},
  "enrichment_status": {"level": "gold", "enriched_at": "2026-03-04T12:00:00Z", "enriched_by": "claude_direct_v2", "source_quality": "ai_generated"}
})

print("=== B183-B186 complete ===")
